Name: Run Thank you for Coming Script
On:
  Push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
Jobs:
  best:
    runs-on: ubuntu-latest
    steps:
      name: Say Greetings
      run: echo "thank you for coming"
