name: run hello my name scripts
on:
  push:
    branches: [ main ]
  pull_request:        
    branches: [ main ] 
jobs:
  Dami:
    runs-on: ubuntu-latest
    steps:
      - name: Damilola
        run: echo "my name is Damilola" 
        
