name: Run mention my name scripts
on:
  push:
    branches: [ main ]
  pull_request:        
    branches: [ main ] 
jobs:
  dami:
    runs-on: ubuntu-latest
    steps:
      - name: Damilola
        run: echo "my name is Damilola" 
        
