name: run hello my name scripts
on:
  push:
    branches: [ main ]
  pull_reqest:        
    branches: [ main ] 
jobs:
  Dami:
    run-on: ubuntu-latest
    steps:
      - name: Damilola
        run: echo "my name is Damilola" 
        
