name: run hello my name scripts
no:
  push:
    branches: [ main ]
  pull_reqests:        
    branches: [ main ] 
jobs:
  Dami:
    run-on: ubuntu-latest
    steps:
      - name: Damilola
        run: echo "my name is Damilola" 
        
