name: run hello my name scripts
no:
  workflow_dispatch:
  push:
    branches: 
      - main
      - dami-actions
   

  pull_reqests:        
    branches: 
      - main
      - dami-actions  

jobs:
  Dami:
    run-on: ubuntu-latest
    steps:
      - name: Damilola
        run: echo "my name is Damilola" 
        

