name: run hello my name scripts
no:
  push:
    branches: [ main ]
  pull_reqests:        
    branches: [ main ]
jobs:
    Dami:
        run-on: ubnntu-latest
        steps:
          - name: mention my name
            run: echo "my name is Damilola" 
        

