name: Mention my name
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - mike-actions

  pull_request:
    branches:
      - main
      - mike-actions

jobs:
  say_myname:
    runs-on: ubuntu-lastest
    steps:
      - name: michael
        run: echo "my name is michael"
